### ISSUE TITLE
Discord invite invalid?

### ISSUE THREAD

**Issue by orbit-loona** [WitherTaco/ClickerAddon#1]
The Discord link given as this mod's homepage \(https://discord.gg/gJPGUpu7) leads to the "Invite Invalid" page.

![image](https://user-images.githubusercontent.com/68935009/118155487-48ca4e80-b3e6-11eb-9dd2-f3ef0cb975dd.png)

**Comment by WitherTaco** [comment]
fixed

**Comment by orbit-loona** [comment]
Thanks.
